server:
  port: 8082

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mange_db?useUnicode=true&characterEncoding=UTF8
    username: mange
    password: Mange@2020
    driver-class-name: com.mysql.cj.jdbc.Driver