

mybatis:
  config-location: classpath:mybatis-config.xml
logging:
  level:
    root: info
    org:
      springframework:
        security: debug
  file:
    path: /Users/yangzhang/IdeaProjects/obsession/logs/
    name: obsession.log

props:
  imageDir: "./"
  zipDir: zipTemp
  bufferSize: 1024

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
